packages:
  - "apps/*"
  - "packages/*"
engineStrict: true
strictPeerDependencies: true
autoInstallPeers: false
saveExact: true
sharedWorkspaceLockfile: true
managePackageManagerVersions: false
verifyDepsBeforeRun: false
overrides:
  fast-uri: 3.1.6
  js-yaml: 4.3.2
  nanoid: 3.3.18
  svgo: 4.1.0
