import { writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import Ajv2020 from "ajv/dist/2020.js"
import standaloneCode from "ajv/dist/standalone/index.js"
import contentDocumentSchema from "../../../contracts/content-document.schema.json" with { type: "json" }

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..")
const outputPath = path.join(
  repositoryRoot,
  "packages/content-schema/src/generated/content-document-validator.ts"
)

const browserSchema = structuredClone(contentDocumentSchema) as unknown as {
  properties: { blocks: { uniqueItems?: boolean } }
}

// The server validator retains JSON Schema's deep uniqueItems check. The
// browser also enforces the stronger block-ID invariant below, so omitting
// uniqueItems keeps the standalone bundle free of AJV's CommonJS deep-equal
// helper and therefore safe to load under a strict CSP.
delete browserSchema.properties.blocks.uniqueItems

const ajv = new Ajv2020({ allErrors: true, strict: true, code: { esm: true, source: true } })
ajv.addFormat("uuid", /^(?:urn:uuid:)?[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i)
ajv.addFormat("uri", /^(?:[a-z][a-z0-9+\-.]*:)(?:\/?\/)?[^\s]*$/i)
const validate = ajv.compile(browserSchema)
const generated = standaloneCode(ajv, validate).replace(
  /const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/,
  (_, name: string) =>
    `const ${name} = (value) => {\n` +
    `  let length = 0;\n` +
    `  for (let position = 0; position < value.length; position += 1) {\n` +
    `    const code = value.charCodeAt(position);\n` +
    `    if (code >= 0xd800 && code <= 0xdbff && position + 1 < value.length) {\n` +
    `      const nextCode = value.charCodeAt(position + 1);\n` +
    `      if ((nextCode & 0xfc00) === 0xdc00) position += 1;\n` +
    `    }\n` +
    `    length += 1;\n` +
    `  }\n` +
    `  return length;\n` +
    `};`
)

if (/require\(|new Function|\beval\s*\(/u.test(generated)) {
  throw new Error("CSP-safe standalone validator contains dynamic/CommonJS code")
}

writeFileSync(
  outputPath,
  [
    "// This file is generated by scripts/generate-browser-validator.ts.",
    "/* eslint-disable */",
    "// @ts-nocheck",
    generated,
    ""
  ].join("\n"),
  "utf8"
)
